import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import AuthWidget from "../components/AuthWidget";
import { FaInstagram, FaFacebook, FaWhatsapp } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script defer src="https://cloud.umami.is/script.js" data-website-id="0e74569e-3f92-4238-8b1f-1160e5685059"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
        <footer className="bg-[#e1f7e3] text-[#034f1d] text-center py-8 mt-auto border-t border-[#65b305]">
          <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 px-4">
            {/* Redes sociales */}
            <div>
              <h3 className="font-bold mb-2 text-[#034f1d]">Redes sociales</h3>
              <div className="flex justify-center gap-4 text-2xl">
                <a href="https://www.instagram.com/concreviv.ar" target="_blank" rel="noopener noreferrer" aria-label="Instagram" className="hover:text-[#65b305] transition-colors"><FaInstagram /></a>
                <a href="https://www.facebook.com/Concreviv" target="_blank" rel="noopener noreferrer" aria-label="Facebook" className="hover:text-[#65b305] transition-colors"><FaFacebook /></a>
                <a href="https://wa.me/5492236897840" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" className="hover:text-[#65b305] transition-colors"><FaWhatsapp /></a>
              </div>
              <div className="mt-2 text-[14px]">
                @concreviv
              </div>
            </div>
            {/* Dirección */}
            <div>
              <h3 className="font-bold mb-2 text-[#034f1d]">Dirección</h3>
              <p className="text-[15px]">Formosa 3133<br/>Mar del Plata, Argentina</p>
              <p className="text-[14px] mt-2">Siempre abierto</p>
              <p className="text-[15px] mt-2">0223 689-7840</p>
              <a href="tel:+5492236897840" className="text-[#65b305] underline text-[15px] block">+54 9 223 689-7840</a>
              <a href="https://concreviv.com.ar" target="_blank" rel="noopener noreferrer" className="text-[#65b305] underline text-[15px] block">concreviv.com.ar</a>
            </div>
            {/* Quiénes somos */}
            <div>
              <h3 className="font-bold mb-2 text-[#034f1d]">Quiénes somos</h3>
              <p className="text-[15px]">Concreviv es una startup argentina dedicada a transformar la construcción de viviendas. Nuestro equipo combina experiencia en arquitectura, ingeniería y tecnología para ofrecer soluciones rápidas, accesibles y de calidad.</p>
            </div>
            {/* Legales */}
            <div>
              <h3 className="font-bold mb-2 text-[#034f1d]">Legales</h3>
              <a href="/terminos-y-condiciones" className="text-[#65b305] underline hover:text-[#034f1d] text-[15px] block mb-1">Términos y condiciones</a>
              <a href="/politica-de-privacidad" className="text-[#65b305] underline hover:text-[#034f1d] text-[15px]">Política de privacidad</a>
            </div>
          </div>
          <div className="text-[13px] text-[#034f1d] mt-6">© {new Date().getFullYear()} CONCREVIV. Todos los derechos reservados.</div>
        </footer>
      </body>
    </html>
  );
}
